Feature - Load more text example
markmead/hyperjs pull request #66
Opened 2024-10-28 11:30 UTC by anwesha2002

this PR adds the feature of Load More component and user can load any data according to its length. It contains two kind of component one is for load more only and another one is for load More and load less.
Addition setup for the project is also taken care of.

issue fixed : #64 

https://github.com/user-attachments/assets/2a153d5c-ff98-4579-93f0-b6886a7391ec

@markmead  please merge this PR under hacktoberfest'24.

2024-10-29 13:52 UTC, markmead requested changes

2024-10-29 13:52 UTC, markmead commented on public/components/LoadMore.html
I don't see the need for this component. It would make sense if it was calling an API and loading items in.

2024-10-29 13:52 UTC, markmead commented on public/components/LoadMore-Less.html
This is not how I'd do it. You could use CSS `line-clamp` and toggle a Tailwind CSS class.

2024-10-29 13:52 UTC, markmead commented on src/data/groups.js
> +  },
Not needed.

2024-10-29 13:52 UTC, markmead commented on src/data/components/LoadMore-Less.mdx
> +group: LoadMore
See this as more of a utility that a new group.

2024-10-29 13:52 UTC, markmead commented on src/components/Sidebar.jsx
> +      {groupIcon === 'ChevronDoubleDownIcon' && <ChevronDoubleDownIcon className="size-4" />}
Not needed.

2024-10-29 23:30 UTC, anwesha2002 commented on public/components/LoadMore-Less.html
okay

2024-10-30 07:32 UTC, anwesha2002 commented on src/data/components/LoadMore-Less.mdx
> +group: LoadMore
can you give me a suggestion how to make it a utility rather than group. Other changes are done

2024-10-30 11:34 UTC, markmead commented on src/data/components/LoadMore-Less.mdx
> +group: LoadMore
Just change it to `group: utility`.

2024-10-31 09:16 UTC, markmead requested changes
Not trying to be vague with my comments, I just can't leave a comment for each change as it would be quicker to redo the component.

2024-10-31 09:16 UTC, markmead commented on package.json
> +    "@tailwindcss/line-clamp": "^0.4.4",
`line-clamp` is part of Tailwind CSS, you don't need to install it.

2024-10-31 09:16 UTC, markmead commented on src/components/Sidebar.jsx
> +  ChevronDoubleDownIcon,
Can remove.

2024-10-31 09:16 UTC, markmead commented on yarn.lock
This file shouldn't be changed.

2024-10-31 09:16 UTC, markmead commented on public/components/LoadMore-Less.html
This is way overkill:

- You don't need the text in a `message` variable in Alpine JS, it can just be within a HTML element
- You should be toggling a `line-clamp-x` class with Alpine JS - https://alpinejs.dev/directives/bind#class-object-syntax

There are a few other things but really, this can be massively simplified. I'd take a look at some Alpine JS docs and the examples on https://js.hyperui.dev and then start again.

2024-10-31 10:31 UTC, anwesha2002 commented on public/components/LoadMore-Less.html
Thank you for your valuable insights but it's not like i didn't try this method of toggling a class using Tailwind css line-clamp but the thing here is it will only be a single step loadmore and less component. User won't get any choice for any successive load according to the content's height .
But as you wish it to be like this I would do it

2024-10-31 10:50 UTC, markmead commented on public/components/LoadMore-Less.html
I have never seen functionality where you can keep clicking "Load more" to view more lines of text, it doesn't exist and for good reason as it's anti-user. Having a "Load more/less" toggle is quite a standard piece of functionality, that is what I'm saying to focus on.

2024-10-31 20:33 UTC, markmead commented
Fixed and cleaned up the PR ready for merge. 

I'm from the UK so I probably wont be online when you do the work and would therefore miss the Hacktoberfest cutoff.

2024-10-31 20:33 UTC, merged